version: 2
updates:
  - package-ecosystem: npm
    directory: /hub-react
    schedule:
      interval: monthly
    groups:
      dependencias:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
